### ISSUE TITLE
ReMemorize Ex: Rated0Search: doesn't work with 2.1.24 and no longer needed in this version

### ISSUE THREAD

**Issue by ijgnd** [lovac42/ReMemorize#25]
This issue is about [ReMemorize Ex: Rated0Search](https://ankiweb.net/shared/info/1056004913).

With Anki 2.1.24 beta5 during startup I get this error message:

    ⁨Traceback (most recent call last):
    File "aqt/addons.py", line 208, in loadAddons
    File "../addons21/1056004913/__init__.py", line 1, in <module>
        from .rated0Search import *
    File "../Anki2/addons21/1056004913/rated0Search.py", line 47, in <module>
        anki.find.Finder._findRated = wrap(anki.find.Finder._findRated, wrap_findRated, 'around')
    AttributeError: type object 'Finder' has no attribute '_findRated'

&nbsp;

I think it's **no longer needed**. A month ago there was a commit to Anki titled [ increase the rated search cap to 365, and allow searches for ease 0 ](https://github.com/ankitects/anki/commit/9696e959be4250145ec6428ee530b1ef6b401194) with the comment "An add-on appears to use ease 0 when rescheduling cards, and it may make sense for Anki to do the same in the future as well."

&nbsp;

Maybe also interesting from the [beta changelog for 2.1.24](https://betas.ankiweb.net/#/?id=changes-in-2124beta1):

> Because the searching code has been rewritten, add-ons that modify the search code will need to be updated to support 2.1.24. Unfortunately it is no longer possible to override the Finder class - add-ons will need to use the new hooks in the browser screen to either rewrite the search text, or perform their own lookups instead.

Once more: Thanks for making this add-on. It has often helped me over the last year.

**Comment by lovac42** [comment]
Thanks for letting me know. Glad to hear some of these ideas are finally merging back with the main branch and lessen the burden on addon authors. This extension is your baby as much as mine.
